url     : https://mashanz.com # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : Hanjara Adhyatma Notes
description: > # this means to ignore newlines until "Language & timezone"
  Your Site Description

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
