url     : https://mashanz.com # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : Han`s Notes
author  : Hanjara
description: > # this means to ignore newlines until "Language & timezone"
  Development notes for everyday use by Hanjara Cahya Adhyatma

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
